@host=http://localhost:258

###

GET {{host}}/

###

# @name config-get
GET {{host}}/api/config-get?key=PATH_PUBLIC

###

# @name file-list
GET {{host}}/api/file-list?folder=/

###

# @name file-check
GET {{host}}/api/file-check?file=/index.html

###

# @name file-download
GET {{host}}/api/file-download?file=/index.html

###

# @name file-upload
POST {{host}}/api/file-upload
Content-Type: application/json

###

# @name cmd
POST {{host}}/api/cmd
Content-Type: application/json

{
	"paths": ["D:/Apps/7-Zip"],
	"command": "7z",
	"args": ["-h"],
	"cwd": "."
}

###

# @name duckdb-info
GET {{host}}/api/duckdb-info

###

# @name duckdb-run
POST {{host}}/api/duckdb-run
Content-Type: application/json

{
	"database": "D:/Projects/MtBunJS/private/mydb.duckdb",
	"sql": "CREATE TABLE users (id INTEGER PRIMARY KEY, name VARCHAR, email VARCHAR, created_at TIMESTAMP DEFAULT current_timestamp)"
}

###

# @name duckdb-run
POST {{host}}/api/duckdb-run
Content-Type: application/json

{
	"database": "D:/Projects/MtBunJS/private/mydb.duckdb",
	"sql": "DROP TABLE users"
}

###

# @name duckdb-run
POST {{host}}/api/duckdb-run
Content-Type: application/json

{
	"database": "D:/Projects/MtBunJS/private/mydb.duckdb",
	"sql": "INSER users()"
}

###

# @name duckdb-query
POST {{host}}/api/duckdb-query
Content-Type: application/json

{
	"database": "D:/Projects/MtBunJS/private/music.duckdb",
	"sql": "SELECT name,rate,duration,array_to_string(tags,',') tags,decibel,trackbegin,trackend,miss FROM music"
}

###

	# "sql": "SELECT name, rate, duration, to_json(tags) tags,decibel,trackbegin,trackend,miss FROM music"
